# Generated by Django 3.0.5 on 2022-07-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_chance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chance',
        ),
    ]
